### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by liushuyu** [AOSC-Dev/acbs#1]
This is a refactor of its ancestor, it still contains a part of its ancestor's code.

- [x] Total code cleanup
- [x] Thorough and extensive testing
- [x] Dinner served, *******s!

**Comment by MingcongBai** [comment]
Appending...

- [x] Searching support.
- [x] Bash (or any other shell, but Bash first) completions.
